// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "gorouter.ErrorInfo": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "gorouter.ErrorResponse": {
                "properties": {
                    "error": {
                        "$ref": "#/components/schemas/gorouter.ErrorInfo"
                    }
                },
                "type": "object"
            },
            "task-service_service_task.AddRequest": {
                "properties": {
                    "BrigadeID": {
                        "type": "integer"
                    },
                    "Comment": {
                        "type": "string"
                    },
                    "ObjectID": {
                        "type": "integer"
                    },
                    "PlanVisitAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "task-service_service_task.AssignToBrigadeRequest": {
                "properties": {
                    "BrigadeID": {
                        "type": "integer"
                    },
                    "TaskID": {
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "task-service_service_task.Status": {
                "enum": [
                    0,
                    1,
                    2,
                    3
                ],
                "type": "integer",
                "x-enum-varnames": [
                    "StatusUnknown",
                    "StatusPlanned",
                    "StatusInWork",
                    "StatusDone"
                ]
            },
            "task-service_service_task.Task": {
                "properties": {
                    "BrigadeID": {
                        "type": "integer"
                    },
                    "Comment": {
                        "type": "string"
                    },
                    "CreatedAt": {
                        "type": "string"
                    },
                    "FinishedAt": {
                        "type": "string"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "ObjectID": {
                        "type": "integer"
                    },
                    "PlanVisitAt": {
                        "type": "string"
                    },
                    "StartedAt": {
                        "type": "string"
                    },
                    "Status": {
                        "$ref": "#/components/schemas/task-service_service_task.Status"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/tasks": {
            "get": {
                "description": "Returns all inspection tasks.",
                "parameters": [
                    {
                        "description": "Maximum number of items to return; 0 means no limit",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Number of items to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/task-service_service_task.Task"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List tasks",
                "tags": [
                    "tasks"
                ]
            },
            "post": {
                "description": "Creates an inspection task for a metering object.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/task-service_service_task.AddRequest",
                                        "summary": "request",
                                        "description": "Task creation payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Task creation payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/task-service_service_task.Task"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create task",
                "tags": [
                    "tasks"
                ]
            }
        },
        "/tasks/assign": {
            "patch": {
                "description": "Assigns an inspection task to an inspector brigade.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/task-service_service_task.AssignToBrigadeRequest",
                                        "summary": "request",
                                        "description": "Assignment payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Assignment payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/task-service_service_task.Task"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Assign task to brigade",
                "tags": [
                    "tasks"
                ]
            }
        },
        "/tasks/brigade/{brigadeID}": {
            "get": {
                "description": "Returns tasks assigned to a brigade.",
                "parameters": [
                    {
                        "description": "Brigade ID",
                        "in": "path",
                        "name": "brigadeID",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Maximum number of items to return; 0 means no limit",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Number of items to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/task-service_service_task.Task"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List tasks by brigade",
                "tags": [
                    "tasks"
                ]
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "Returns an inspection task by identifier.",
                "parameters": [
                    {
                        "description": "Task ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/task-service_service_task.Task"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get task by ID",
                "tags": [
                    "tasks"
                ]
            }
        },
        "/tasks/{id}/start": {
            "patch": {
                "description": "Marks a planned task as started.",
                "parameters": [
                    {
                        "description": "Task ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/task-service_service_task.Task"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Start task",
                "tags": [
                    "tasks"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/api/task-service"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Task Service API",
	Description:      "API for managing inspection tasks and brigade assignments.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
